import type { Metadata } from "next";
import "./globals.css";
import { CursorGlow } from "./CursorGlow";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <CursorGlow />
        {children}
      </body>
    </html>
  );
}
